In [18]:
import pandas as pd
import numpy as np
import sklearn as sk
import statsmodels as sm
import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
abalone = pd.read_csv("./abalone.data", header=None)

In [20]:
abalone.head()

   0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7

In [21]:
#add names to cilumns
abalone.columns = ['Sex','length','diameter','height','wholeweight',
                'shuckedweight','visceraweight','shellweight','rings']

In [22]:
abalone.head()

,Sex,length,diameter,height,wholeweight,shuckedweight,visceraweight,shellweight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [23]:
abalone.describe()

,length,diameter,height,wholeweight,shuckedweight,visceraweight,shellweight,rings
count,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000,4177.000000
mean,0.523992,0.407881,0.139516,0.828742,0.359367,0.180594,0.238831,9.933684
std,0.120093,0.099240,0.041827,0.490389,0.221963,0.109614,0.139203,3.224169
min,0.075000,0.055000,0.000000,0.002000,0.001000,0.000500,0.001500,1.000000
25%,0.450000,0.350000,0.115000,0.441500,0.186000,0.093500,0.130000,8.000000
50%,0.545000,0.425000,0.140000,0.799500,0.336000,0.171000,0.234000,9.000000
75%,0.615000,0.480000,0.165000,1.153000,0.502000,0.253000,0.329000,11.000000
max,0.815000,0.650000,1.130000,2.825500,1.488000,0.760000,1.005000,29.000000

In [24]:
#abalone height has some 0 in it. That is not possible. Let's have a look at that data
abalone['height'][abalone['height'] == 0]

1257    0
3996    0
Name: height, dtype: float64

In [25]:
#let's avoid them
abalone['height'][abalone['height'] == 0] = np.nan

c:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [26]:
#pairwise correlation
abalone.corr()

,length,diameter,height,wholeweight,shuckedweight,visceraweight,shellweight,rings
length,1.000000,0.986812,0.828108,0.925261,0.897914,0.903018,0.897706,0.556720
diameter,0.986812,1.000000,0.834298,0.925452,0.893162,0.899724,0.905330,0.574660
height,0.828108,0.834298,1.000000,0.819886,0.775621,0.798908,0.819596,0.557625
wholeweight,0.925261,0.925452,0.819886,1.000000,0.969405,0.966375,0.955355,0.540390
shuckedweight,0.897914,0.893162,0.775621,0.969405,1.000000,0.931961,0.882617,0.420884
visceraweight,0.903018,0.899724,0.798908,0.966375,0.931961,1.000000,0.907656,0.503819
shellweight,0.897706,0.905330,0.819596,0.955355,0.882617,0.907656,1.000000,0.627574
rings,0.556720,0.574660,0.557625,0.540390,0.420884,0.503819,0.627574,1.000000